// // Helper to inject our "Nuclear Patches" for WebContainer stability

// export function applySafetyOverrides(fileTree: any, addLog: (msg: string) => void) {
//   // 1. Force Babel (Fixes SWC Crash)
//   fileTree['.babelrc'] = JSON.stringify({
//     "presets": ["next/babel"]
//   });

//   // 2. Hardcode Next Config (Fixes ESM/CJS issues)
//   fileTree['next.config.mjs'] = `
// /** @type {import('next').NextConfig} */
// const nextConfig = {
//   reactStrictMode: true,
//   swcMinify: false, // Force Babel
// };
// export default nextConfig;
//   `.trim();

//   // 3. Hardcode PostCSS Config (Fixes "SyntaxError: Unexpected token")
//   fileTree['postcss.config.js'] = `
// module.exports = {
//   plugins: {
//     tailwindcss: {},
//     autoprefixer: {},
//   },
// };
//   `.trim();

//   // 4. Hardcode Tailwind Config
//   fileTree['tailwind.config.ts'] = `
// import type { Config } from "tailwindcss";
// const config: Config = {
//   content: [
//     "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
//     "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
//     "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
//   ],
//   theme: {
//     extend: {
//       colors: {
//         background: "var(--background)",
//         foreground: "var(--foreground)",
//       },
//     },
//   },
//   plugins: [],
// };
// export default config;
//   `.trim();

//   // 5. Inject Missing Dependencies
//   try {
//     let pkg;
//     const pkgData = fileTree['package.json'];
    
//     if (typeof pkgData === 'object' && pkgData !== null) {
//       pkg = pkgData;
//     } else if (typeof pkgData === 'string') {
//       pkg = JSON.parse(pkgData);
//     } else {
//        pkg = { dependencies: {}, scripts: { dev: "next dev" } };
//     }

//     pkg.dependencies = pkg.dependencies || {};
//     pkg.dependencies['@babel/runtime'] = 'latest';
//     pkg.dependencies['@babel/plugin-transform-runtime'] = 'latest';
//     pkg.dependencies['tailwindcss'] = 'latest';
//     pkg.dependencies['postcss'] = 'latest';
//     pkg.dependencies['autoprefixer'] = 'latest';

//     fileTree['package.json'] = JSON.stringify(pkg, null, 2);
//     addLog('🛡️ SYSTEM: Config files overwritten with stable versions.');
//   } catch (e) {
//     console.error("Patch failed", e);
//   }

//   // 6. SANITIZER: Kill 'next/font'
//   const layoutPath = 'src/app/layout.tsx';
//   if (fileTree[layoutPath] && fileTree[layoutPath].includes('next/font')) {
//     addLog('⚠️ DETECTED BANNED FONT. Sanitizing layout...');
//     fileTree[layoutPath] = `
// import './globals.css';
// export const metadata = { title: 'App', description: 'Generated by AI' };
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
//     `.trim();
//   }
// }



















const STABLE_NEXT_CONFIG = `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: false, // ⚠️ CRITICAL: Forces Babel
};
export default nextConfig;
`.trim();

const STABLE_POSTCSS_CONFIG = `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`.trim();

const STABLE_TAILWIND_CONFIG = `
import type { Config } from "tailwindcss";
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};
export default config;
`.trim();

const SAFE_LAYOUT_CONTENT = `
import './globals.css';
export const metadata = { title: 'App', description: 'Generated by AI' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`.trim();

// 🛑 STOP SWC DOWNLOADS GLOBALLY
const NPM_RC_CONFIG = `
optional=false
audit=false
fund=false
update-notifier=false
loglevel=error
`.trim();

const REQUIRED_DEPENDENCIES = [
  '@babel/runtime',
  '@babel/plugin-transform-runtime',
  'tailwindcss',
  'postcss',
  'autoprefixer'
];

export function applySafetyOverrides(fileTree: Record<string, any>, addLog: (msg: string) => void) {
  // 1. Inject Global NPM Config (The Shield)
  fileTree['.npmrc'] = NPM_RC_CONFIG;

  // 2. Force Configuration Files
  fileTree['.babelrc'] = JSON.stringify({ presets: ["next/babel"] });
  fileTree['next.config.mjs'] = STABLE_NEXT_CONFIG;
  fileTree['postcss.config.js'] = STABLE_POSTCSS_CONFIG;
  fileTree['tailwind.config.ts'] = STABLE_TAILWIND_CONFIG;

  // 3. Patch package.json
  try {
    let pkg;
    const pkgData = fileTree['package.json'];

    if (typeof pkgData === 'object' && pkgData !== null) {
      pkg = pkgData;
    } else if (typeof pkgData === 'string') {
      pkg = JSON.parse(pkgData);
    } else {
      pkg = { dependencies: {}, scripts: { dev: "next dev" } };
    }

    pkg.dependencies = pkg.dependencies || {};
    pkg.devDependencies = pkg.devDependencies || {};

    // 🛡️ SWC KILLER: Remove any SWC-related packages
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    Object.keys(allDeps).forEach(dep => {
        if (dep.includes('swc') || dep.includes('next-swc')) {
            delete pkg.dependencies[dep];
            delete pkg.devDependencies[dep];
        }
    });
    
    // Add required dependencies
    REQUIRED_DEPENDENCIES.forEach(dep => {
      pkg.dependencies[dep] = 'latest';
    });

    fileTree['package.json'] = JSON.stringify(pkg, null, 2);
    addLog('🛡️ SYSTEM: Config files & dependencies sanitized.');
  } catch (error) {
    console.error("Patch failed", error);
  }

  // 4. Layout Sanitizer
  const layoutPath = 'src/app/layout.tsx';
  if (fileTree[layoutPath] && fileTree[layoutPath].includes('next/font')) {
    addLog('⚠️ DETECTED BANNED FONT. Sanitizing layout...');
    fileTree[layoutPath] = SAFE_LAYOUT_CONTENT;
  }
}
