

















// const STABLE_NEXT_CONFIG = `
// /** @type {import('next').NextConfig} */
// const nextConfig = {
//   reactStrictMode: true,
//   swcMinify: false, // ⚠️ CRITICAL: Forces Babel
// };
// export default nextConfig;
// `.trim();

// const STABLE_POSTCSS_CONFIG = `
// module.exports = {
//   plugins: {
//     tailwindcss: {},
//     autoprefixer: {},
//   },
// };
// `.trim();

// const STABLE_TAILWIND_CONFIG = `
// import type { Config } from "tailwindcss";
// const config: Config = {
//   content: [
//     "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
//     "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
//     "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
//   ],
//   theme: {
//     extend: {
//       colors: {
//         background: "var(--background)",
//         foreground: "var(--foreground)",
//       },
//     },
//   },
//   plugins: [],
// };
// export default config;
// `.trim();

// const SAFE_LAYOUT_CONTENT = `
// import './globals.css';
// export const metadata = { title: 'App', description: 'Generated by AI' };
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
// `.trim();

// // 🛑 STOP SWC DOWNLOADS GLOBALLY
// const NPM_RC_CONFIG = `
// optional=false
// audit=false
// fund=false
// update-notifier=false
// loglevel=error
// `.trim();

// const REQUIRED_DEPENDENCIES = [
//   '@babel/runtime',
//   '@babel/plugin-transform-runtime',
//   'tailwindcss',
//   'postcss',
//   'autoprefixer'
// ];

// export function applySafetyOverrides(fileTree: Record<string, any>, addLog: (msg: string) => void) {
//   // 1. Inject Global NPM Config (The Shield)
//   fileTree['.npmrc'] = NPM_RC_CONFIG;

//   // 2. Force Configuration Files
//   fileTree['.babelrc'] = JSON.stringify({ presets: ["next/babel"] });
//   fileTree['next.config.mjs'] = STABLE_NEXT_CONFIG;
//   fileTree['postcss.config.js'] = STABLE_POSTCSS_CONFIG;
//   fileTree['tailwind.config.ts'] = STABLE_TAILWIND_CONFIG;

//   // 3. Patch package.json
//   try {
//     let pkg;
//     const pkgData = fileTree['package.json'];

//     if (typeof pkgData === 'object' && pkgData !== null) {
//       pkg = pkgData;
//     } else if (typeof pkgData === 'string') {
//       pkg = JSON.parse(pkgData);
//     } else {
//       pkg = { dependencies: {}, scripts: { dev: "next dev" } };
//     }

//     pkg.dependencies = pkg.dependencies || {};
//     pkg.devDependencies = pkg.devDependencies || {};

//     // 🛡️ SWC KILLER: Remove any SWC-related packages
//     const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
//     Object.keys(allDeps).forEach(dep => {
//         if (dep.includes('swc') || dep.includes('next-swc')) {
//             delete pkg.dependencies[dep];
//             delete pkg.devDependencies[dep];
//         }
//     });
    
//     // Add required dependencies
//     REQUIRED_DEPENDENCIES.forEach(dep => {
//       pkg.dependencies[dep] = 'latest';
//     });

//     fileTree['package.json'] = JSON.stringify(pkg, null, 2);
//     addLog('🛡️ SYSTEM: Config files & dependencies sanitized.');
//   } catch (error) {
//     console.error("Patch failed", error);
//   }

//   // 4. Layout Sanitizer
//   const layoutPath = 'src/app/layout.tsx';
//   if (fileTree[layoutPath] && fileTree[layoutPath].includes('next/font')) {
//     addLog('⚠️ DETECTED BANNED FONT. Sanitizing layout...');
//     fileTree[layoutPath] = SAFE_LAYOUT_CONTENT;
//   }
// }











const STABLE_NEXT_CONFIG = `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: false, // ⚠️ CRITICAL: Forces Babel
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
};
export default nextConfig;
`.trim();

const STABLE_POSTCSS_CONFIG = `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`.trim();

const STABLE_TAILWIND_CONFIG = `
import type { Config } from "tailwindcss";
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};
export default config;
`.trim();

const SAFE_LAYOUT_CONTENT = `
import './globals.css';
export const metadata = { title: 'App', description: 'Generated by AI' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`.trim();

// 🛑 STOP SWC DOWNLOADS GLOBALLY
const NPM_RC_CONFIG = `
optional=false
audit=false
fund=false
update-notifier=false
loglevel=error
`.trim();

const REQUIRED_DEPENDENCIES = [
  '@babel/runtime',
  '@babel/plugin-transform-runtime',
  'tailwindcss',
  'postcss',
  'autoprefixer'
];

export function applySafetyOverrides(fileTree: Record<string, any>, addLog: (msg: string) => void) {
  // 1. CLEANUP: Delete conflicting configs
  // If we are forcing next.config.mjs, we MUST delete next.config.js or it crashes
  if (fileTree['next.config.js']) {
    delete fileTree['next.config.js'];
    addLog('🗑️ Deleted conflicting next.config.js');
  }
  if (fileTree['tailwind.config.js']) {
    delete fileTree['tailwind.config.js'];
  }

  // 2. INJECT: Force Global Configs
  fileTree['.npmrc'] = NPM_RC_CONFIG;
  fileTree['.babelrc'] = JSON.stringify({ presets: ["next/babel"] });
  fileTree['next.config.mjs'] = STABLE_NEXT_CONFIG;
  fileTree['postcss.config.js'] = STABLE_POSTCSS_CONFIG;
  fileTree['tailwind.config.ts'] = STABLE_TAILWIND_CONFIG;

  // 3. PATCH: Sanitize package.json
  try {
      let pkg;
      const pkgData = fileTree['package.json'];

      // Parse existing or create new
      if (typeof pkgData === 'object' && pkgData !== null) pkg = pkgData;
      else if (typeof pkgData === 'string') pkg = JSON.parse(pkgData);
      else pkg = {};

      // Initialize sections
      pkg.dependencies = pkg.dependencies || {};
      pkg.devDependencies = pkg.devDependencies || {};
      pkg.scripts = pkg.scripts || { "dev": "next dev", "build": "next build", "start": "next start" };
      pkg.name = "ai-app";

      // 🛡️ VERSION PINNING (The Downgrade Fix)
      // Next.js 14.2+ is hostile to WebContainers. We pin 13.5.6 for stability.
      pkg.dependencies['next'] = '13.5.6'; 
      pkg.dependencies['react'] = '18.2.0';
      pkg.dependencies['react-dom'] = '18.2.0';
      
      // Force Babel dependencies
      REQUIRED_DEPENDENCIES.forEach(dep => {
        pkg.dependencies[dep] = 'latest';
      });

      // 🛡️ SWC KILLER LOOP
      const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
      Object.keys(allDeps).forEach(dep => {
          if (dep.includes('swc') || dep.includes('next-swc') || dep.includes('sharp')) {
              delete pkg.dependencies[dep];
              delete pkg.devDependencies[dep];
          }
      });

      fileTree['package.json'] = JSON.stringify(pkg, null, 2);
      addLog('🛡️ SYSTEM: Downgraded Next.js to stable 13.5.6 compatible version.');
    } catch (error) {
      console.error("Patch failed", error);
    }

  // 4. SANITIZE: Layout File (Kill next/font)
  const layoutPath = 'src/app/layout.tsx';
  if (fileTree[layoutPath] && fileTree[layoutPath].includes('next/font')) {
    addLog('⚠️ DETECTED BANNED FONT. Sanitizing layout...');
    fileTree[layoutPath] = SAFE_LAYOUT_CONTENT;
  }
}