// export const BACKUP_FILES = {
//   "package.json": JSON.stringify({
//     name: "backup-app",
//     scripts: { dev: "next dev", build: "next build", start: "next start" },
//     dependencies: { 
//       "next": "14.2.3", 
//       "react": "18.3.1", 
//       "react-dom": "18.3.1",
//       "lucide-react": "latest"
//     }
//   }, null, 2),
//   "next.config.mjs": "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;",
//   ".babelrc": "{\n  \"presets\": [\"next/babel\"]\n}",
//   "src/app/layout.tsx": "export default function RootLayout({ children }) { return <html lang='en'><body>{children}</body></html> }",
//   "src/app/page.tsx": "export default function Page() { return <div style={{padding: 50, fontFamily: 'sans-serif'}}><h1>⚠️ AI Generation Failed</h1><p>But the System Auto-Healed! Here is a fallback app.</p></div> }"
// };






export const BACKUP_FILES = {
  "package.json": JSON.stringify({
    name: "backup-app",
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies: { 
      "next": "14.2.3", 
      "react": "18.3.1", 
      "react-dom": "18.3.1",
      "lucide-react": "latest",
      "clsx": "latest",
      "tailwind-merge": "latest",
      "tailwindcss": "latest",
      "postcss": "latest",
      "autoprefixer": "latest",
      "@babel/runtime": "latest",
      "@babel/plugin-transform-runtime": "latest"
    }
  }, null, 2),

  ".babelrc": JSON.stringify({
    "presets": ["next/babel"]
  }, null, 2),

  "next.config.mjs": `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: false,
};
export default nextConfig;
  `.trim(),

  "postcss.config.js": `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
  `.trim(),

  "tailwind.config.ts": `
import type { Config } from "tailwindcss";
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
  `.trim(),

  "src/app/globals.css": `
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background-color: #0a0a0a;
  color: #ededed;
}
  `.trim(),

  "src/app/layout.tsx": `
import './globals.css';
export const metadata = { title: 'Backup App', description: 'Generated by System' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
  `.trim(),

  "src/app/page.tsx": `
import { AlertTriangle } from 'lucide-react';

export default function Page() { 
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-neutral-950 text-white p-4 text-center font-sans">
      <div className="bg-red-900/20 border border-red-800 p-8 rounded-xl flex flex-col items-center max-w-md">
        <AlertTriangle size={48} className="text-red-500 mb-4" />
        <h1 className="text-2xl font-bold mb-2">AI Generation Failed</h1>
        <p className="text-neutral-400 mb-6">
          The Neural Link was interrupted, but the Auto-Healer kicked in.
          This is a fallback application to prevent a total crash.
        </p>
        <button className="px-4 py-2 bg-red-600 hover:bg-red-700 rounded text-sm font-medium transition-colors">
          Try Regenerating
        </button>
      </div>
    </div>
  ) 
}
  `.trim()
};